apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}

spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  - name: admin
    port: {{ .Values.service.adminPort }}
    targetPort: {{ .Values.service.adminPort }}
  {{- with .Values.service.debug }}
   {{- if .enabled }}
  - name: debug
    port: {{ .port }}
    targetPort: {{ .port }}
   {{- end }}
  {{- end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
