apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.name" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  RABBITMQ_HOST: {{ .Values.rabbitmq.host | quote }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.password | quote }}
  RABBITMQ_USERNAME: {{ .Values.rabbitmq.username | quote }}
  RABBITMQ_PORT: {{ .Values.rabbitmq.port | quote }}
  QUARKUS_CONSUL_CONFIG_AGENT_HOST_PORT: "{{ .Values.consul.host }}:{{ .Values.consul.port }}"
  QUARKUS_HTTP_ACCESS_LOG_ENABLED: {{ .Values.config.httpAccessLog.enabled | quote }}
  QUARKUS_HTTP_ACCESS_LOG_PATTERN: {{ .Values.config.httpAccessLog.pattern | quote }}
  QUARKUS_HTTP_LIMITS_MAX_BODY_SIZE: '10240K'
