apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.name" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  RABBITMQ_HOST: {{ .Values.rabbitmq.host | quote }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.password | quote }}
  RABBITMQ_USERNAME: {{ .Values.rabbitmq.username | quote }}
  RABBITMQ_PORT: {{ .Values.rabbitmq.port | quote }}

  QUARKUS_CONSUL_CONFIG_AGENT_HOST_PORT: "{{ .Values.consul.host }}:{{ .Values.consul.port }}"
  QUARKUS_DATASOURCE_REACTIVE_URL: {{ .Values.postgresql.reactiveUrl | quote }}
  QUARKUS_DATASOURCE_USERNAME: {{ .Values.postgresql.username | quote }}
  QUARKUS_DATASOURCE_PASSWORD: {{ .Values.postgresql.password | quote }}
  QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: 'update'
  QUARKUS_HTTP_ACCESS_LOG_ENABLED: {{ .Values.config.httpAccessLog.enabled | quote }}
  QUARKUS_HTTP_ACCESS_LOG_PATTERN: {{ .Values.config.httpAccessLog.pattern | quote }}

  SERVICE_DISCOVERY_REGISTRATION_SERVICE_ADDRESS: "{{ template "common.names.name" . }}.{{ .Release.Namespace }}"
  SERVICE_DISCOVERY_REGISTRATION_SERVICE_PORT: {{ .Values.service.port | quote }}

  QUARKUS_REST_CLIENT_PLUGIN_DRIVER_URL: {{ include "helper.pluginDriverURL" . | quote }}
