apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "common.names.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if (or .Values.commonAnnotations .Values.config.annotations) }}
      annotations: 
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 8 }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.config.annotations "context" $ ) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.matchLabels" . | nindent 8 }}
    spec:
      {{- include "common.images.renderPullSecrets" . | nindent 6 }}
      #serviceAccountName: {{ template "common.names.serviceAccountName" . }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ template "common.images.fullname" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          # command: ['sh', '-c', '/wait && karaf run debug']
          #command:
          #  - tail
          #  - "-f"
          #  - /dev/null
          envFrom:
            - configMapRef:
                name: {{ template "common.names.name" . }}-config
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
            - name: admin
              containerPort: {{ .Values.service.adminPort }}
          volumeMounts:
            - mountPath: /karaf/configs
              name: openk9-configs
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cd /karaf/configs && cp *.cfg *.json /karaf/etc"]
      volumes:
      - name: openk9-configs
        configMap:
          name: {{ template "common.names.name" . }}-karaf-config
          items:
            - key: io.openk9.entity.manager.client.internal.EntityManagerClientImpl.cfg
              path: io.openk9.entity.manager.client.internal.EntityManagerClientImpl.cfg
            - key: io.openk9.entity.manager.pub.sub.binding.internal.EntityManagerResponseBinding.json
              path: io.openk9.entity.manager.pub.sub.binding.internal.EntityManagerResponseBinding.json
            - key: io.openk9.ingestion.rabbitmq.RabbitMQActivator.cfg
              path: io.openk9.ingestion.rabbitmq.RabbitMQActivator.cfg
            - key: io.openk9.internal.http.ReactorNettyActivator.cfg
              path: io.openk9.internal.http.ReactorNettyActivator.cfg
            - key: io.openk9.plugins.applications.driver.ApplicationPluginDriver.cfg
              path: io.openk9.plugins.applications.driver.ApplicationPluginDriver.cfg
            - key: io.openk9.plugins.email.driver.EmailPluginDriver.cfg
              path: io.openk9.plugins.email.driver.EmailPluginDriver.cfg
            - key: io.openk9.plugins.email.enrichprocessor.EmailNerEnrichProcessor.cfg
              path: io.openk9.plugins.email.enrichprocessor.EmailNerEnrichProcessor.cfg
            - key: io.openk9.plugins.web.generic.driver.GenericWebPluginDriver.cfg
              path: io.openk9.plugins.web.generic.driver.GenericWebPluginDriver.cfg
            - key: io.openk9.plugins.web.generic.enrichprocessor.WebNerEnrichProcessor.cfg
              path: io.openk9.plugins.web.generic.enrichprocessor.WebNerEnrichProcessor.cfg
            - key: io.openk9.plugins.web.sitemap.driver.SitemapWebPluginDriver.cfg
              path: io.openk9.plugins.web.sitemap.driver.SitemapWebPluginDriver.cfg
            - key: io.openk9.plugins.web.sitemap.enrichprocessor.WebNerEnrichProcessor.cfg
              path: io.openk9.plugins.web.sitemap.enrichprocessor.WebNerEnrichProcessor.cfg
            - key: io.openk9.search.enrich.internal.EndEnrichProcessorImpl.json
              path: io.openk9.search.enrich.internal.EndEnrichProcessorImpl.json
            - key: io.openk9.vertx.internal.consul.VertxConsulActivator.json
              path: io.openk9.vertx.internal.consul.VertxConsulActivator.json
            - key: io.openk9.vertx.internal.consul.VertxConsulActivator.cfg
              path: io.openk9.vertx.internal.consul.VertxConsulActivator.cfg
            - key: io.openk9.vertx.internal.discovery.VertxServiceDiscoveryActivator.json
              path: io.openk9.vertx.internal.discovery.VertxServiceDiscoveryActivator.json
              
