apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-ca
spec:
  isCA: true
  commonName: "*.openk9.local"
  secretName: selfsigned-ca-secret
  dnsNames:
    - "*.openk9.local"
    - ".openk9.local"
    - "openk9.local"
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: openk9-ca-issuer
spec:
  ca:
    secretName: selfsigned-ca-secret